### ISSUE TITLE
[Item] Hearth of the Archmage

### ISSUE THREAD

**Issue by zelding** [AngelArenaAllstars/suggestions#176] opened 2017-02-13 17:30 UTC
**Builds from**:

It is basically HoT but with mana in mind.

- Mystic staff
- Energy booster
- Recipe

**Gives**:
- intelligence
- mana
- manaregen based on your max mana

**Comment by Wujekklawy** [comment] 2017-02-13 19:22
Equivalent of HoT is a Bloodstone so i dumno it is necessary to have item like that

**Comment by zelding** [comment] 2017-02-13 19:30
I admit they are quite similar, but this Item would satisfy the needs of a very mana-hungry hero (such as Skywrath or CM), I can imagine some players would pick up this one, instead of Bloodstone.

Anyway, it would be a nice alternative imho, also could start a different upgrade branch.

**Comment by VoidsKeeper** [comment] 2017-02-13 21:23
Thanks for your idea ;)
Sounds cool. I like your way of solving mana-issues. Could be an upgraded bloodstone, that specifics on mana. Wrote it down :)

**Comment by zelding** [comment] 2017-02-13 22:58
> that specifics on mana

I just gave up giving you numbers; there is no point :roll_eyes:

**Comment by Haganeko** [comment] 2017-04-13 03:48
Thank you for the suggestion! This is a duplicate of #117, item K. Closed.

**Closed as completed by Haganeko** 2017-04-13 03:48 UTC
Labels: duplicate, item
